default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: heroku-connect-rails-demo_development

test:
  <<: *default
  database: heroku-connect-rails-demo_test

production:
  <<: *default
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  url: <%= ENV['DATABASE_URL'] %>
